### ISSUE TITLE
could not compile

### ISSUE THREAD

**Issue by tm-sanjay** [stefaandesmet2003/sduino#1]
Arduino: 1.8.12 (Windows 10), Board: "STM8S103F3 Breakout Board"

exec: "C:\\Users\\Sanjay\\AppData\\Local\\Arduino15\\packages\\sduino\\tools\\STM8Tools\\2019.02.05/win/busybox": file does not exist
Error compiling for board STM8S103F3 Breakout Board.

I'm trying I2C receive example

**Comment by stefaandesmet2003** [comment]
Looks like a setup issue under Windows. I'm using Linux.
