### ISSUE TITLE
Add SoftPWM support

### ISSUE THREAD

**Issue by Pixtxa** [stefaandesmet2003/sduino#2]
Hi,

I think it should be possible to support [SoftPWM](https://github.com/bhagman/SoftPWM) on STM8S003, but I don't know how. Can it be added easily?

Thanks

**Comment by stefaandesmet2003** [comment]
Hi,
Have a look at the tone.c file in this repo. It shows how to setup timer2 and use its ISR to toggle a pin. 
The same principle is used in the SoftPWM library. 
With that you should manage to modify it for stm8. Good luck !

**Comment by Pixtxa** [comment]
Ok, I didn't really get SoftPWM to work, but I can simply change tone.c to fit my needs, which is enough for me. When choosing the right timing I should also be able to implement a serial receiver using the same timer. Thanks.
