### ISSUE TITLE
Interrupt master I2C implementation

### ISSUE THREAD

**Issue by rtek1000** [stefaandesmet2003/sduino#3]
Hello,

Could you tell me which files are involved in the I2C interrupt?

I've tried to implement the interrupt but I still can't, the support for I2C master in the sduino core is not correctly implemented. I was also unable to read using register pulls. I just managed to implement writing.

https://github.com/tenbaht/sduino/issues/143

**Comment by stefaandesmet2003** [comment]
Hi @rtek1000,
I've been using the wire library for my stm8 projects. This library doesn't use i2c interrupts for master i2c, but polling. For me this works reliably (both read & write)
I added slave i2c using interrupts (based on the same ST document that you mentioned). The same ST code has interrupt based master i2c too. I started to integrate that in my version of the wire library, but lost interest (have a look at the #if 0 sections in the code), given that the polling version works ok. Furthermore the combined master/slave i2c code was often taking too much flash space, so for each project I ended up creating separate file versions for master or slave i2c according to the need.

So many months later I can't remember in which state I left it behind, but feel free to try it out.

**Comment by stefaandesmet2003** [comment]
Sorry, awkward typing on a mobile:/

**Comment by stefaandesmet2003** [comment]
I2C_GetFlagStatus() is SPL, haven't tried that with sduino, so can't comment on that. But I'd stick with the default sduino code base, it's optimized for the limited flash size available.

**Comment by rtek1000** [comment]
> Why not use the examples provided with the wire library port included in the sduino repo?
> They work.

https://github.com/tenbaht/sduino/tree/development/sduino/stm8/libraries/Wire

Thanks for the feedback!
