### ISSUE TITLE
issues with data/arrays and I2C

### ISSUE THREAD

**Issue by kokospalme** [stefaandesmet2003/sduino#4]
hello:)

I have a strange issue using I2C functionality. With this examplecode everything works fine:
```
#include <Wire.h>

#define I2C_ADDRESS 0x50 // I2C address

uint8_t wirebuffer[4];   //buffer for sending some bytes
void requestEvent();

void setup() {
  Wire_beginSlave(I2C_ADDRESS);                // join i2c bus with address #8
  Wire_onRequest(requestEvent); // register event
}

void loop() {
  delay(10);
}

// function that executes whenever data is requested by master
// this function is registered as an event, see setup()
void requestEvent() {
  Wire_write_s("hello "); // respond with message of 6 bytes
}
```

But when I change ```void request()```to this:
```
void requestEvent() {
  Wire_write_sn(wirebuffer,4);
}
```
The microcontroller isn't even found in the I2C network (using the I2C scanner sketch on an STM32). Even when I use ```wirebuffer[1] = 4;``` in ```void setup()```, this issue happens. The device also isn't found when using the EEPROM-sketch.
Where could this problem come from? Does anyone else facing this?

**Comment by stefaandesmet2003** [comment]
Strange issue. Wire_write_s is using  Wire_write_sn (wire.c)
If the unmodified slave_eeprom sketch doesn't work for you, there may be a problem with your setup. Checked I2C signals? Best to use a (cheap) logic analyzer, the I2C slave code is running from interrupt, so hard to debug

**Comment by kokospalme** [comment]
Thank for the quick reply. I'll get an I2c analyzer and report the results to this thread soon

**Comment by kokospalme** [comment]
Another interesting fact is, that if the STM8 is master and another MCU as a receiving slave, everything works fine...
When the default Arduino I2C-scanner sketch runs, it never gets a result:
```
I2C Scanner
Scanning...
```
runs forever, or until I cut the wires. Other Slaves in the network are also not recognized if the STM8-Slave is on the network.

As Masters I use an STM32 or an Arduino with levelshifters

**Comment by stefaandesmet2003** [comment]
Do you have pull-ups in your setup?

**Comment by kokospalme** [comment]
of course. I tried 2.2k, 4.7k and 10k with same results. What is your hardwaresetup?

could it be a software-problem? I had to install the [original sduino board](https://github.com/tenbaht/sduino) and change the folder of the [Wire library](https://github.com/stefaandesmet2003/sduino/tree/master/hardware/stm8/0.5.0/libraries/Wire) manually, because the Arduino IDE refused to install your sduino repository...

**Comment by stefaandesmet2003** [comment]
Correct, my repo is only part of the complete sduino repo, with my own modifications.
There's maybe changes I forgot to mention in the readme notes, but you did uncomment the I2C interrupt handler in stm8_it.h ?
slave I2C uses this inthandler, as in the ST reference code. Master I2C was implemented using polling in the original sduino repo, I didn't bother to change that.

**Comment by kokospalme** [comment]
Wow, that was the solution. I uncomment ```INTERRUPT_HANDLER(I2C_IRQHandler, 19);                   /* I2C */```in ```stm8_it.h```. Sorry I didn't read your readme properly, and many many thanks for the support.
